name: Node.js build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: docker login
env:
  username: ${{ secrets.DOCKER_USERNAME }}
  password: ${{ secrets.DOCKER_PASSWORD }}
run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
name: Node js build 
run: |
docker build -t binaydocker27/nodejs:1.0.0 .
